### ISSUE TITLE
Windows - not processing

### ISSUE THREAD

**Issue by c9mbundy** [remove-bg/go#1]
I tried to use the release version of removebg.exe as I don't have GO or its dependencies to build my own.

I ran this command from windows:
`removebg --api-key abcdefg --size hd --output-directory output input\*.*`

and recieved an error message: 
`time="2019-05-16T07:53:35+10:00" level=warning msg="Skipped image" existing="output\\*.png" image=1/1 input="input\\*.*"`

It's not clear from that msg what the problem is, but is the `\\` as expected?

**Comment by odlp** [comment]
Hi @c9mbundy thanks for raising the issue and the detailed explanation.

I've released a new version of the CLI ([`v1.1.0`](https://github.com/remove-bg/go/releases/tag/v1.1.0)) which adds wildcard support (like `input\*.*`) for Windows (sorry this didn't work on Windows using the initial version).

Please could you try the new version and let me know if it resolves the issue?

Many thanks,
Oli

**Comment by odlp** [comment]
Closing this issue, but please do let me know if `v1.1.0` doesn't resolve the issue.
