### ISSUE TITLE
Images reprocessed and credits used without specifying --reprocess-existing flag

### ISSUE THREAD

**Issue by timgp** [remove-bg/go#16]
Command used:
```
$ removebg --api-key <KEY> --extra-api-options crop=true --output-directory bg-removed/ files/*
```

Files already existed:
```
$ find .
./bg-removed
./bg-removed/014D6E0C-CCE2-460C-9E12-7E74BC697B7F.png
./files
./files/014D6E0C-CCE2-460C-9E12-7E74BC697B7F.jpeg
```

Yet the files seem to have been sent to the server again and the timestamps on the files in the `bg-removed` directory are fresh. I'm down about 40 credits too. :(

**Comment by odlp** [comment]
Hi @timgp, 

Thanks for raising this issue and apologies for the inconvenience. I've released a fix in version 1.3.1.

Please do contact customer service if you haven't done so already to reinstate your credits.

Thanks,
Oli
