### ISSUE TITLE
ask for help 

### ISSUE THREAD

**Issue by zcdliuwei** [remove-bg/go#19]
Hi，what a interesting show! When I use the CLI tool like below:
removebg /Users/liuwei/Desktop/lowpoly/BIBAI1995090.png --api-key cr8CWXvHRZQDo4NYZLBa4UpW --output-directory /Users/liuwei/Desktop/removebg --format jpg --bg-color fff  --reprocess-existing

I got a mistake like this: ERRO[0002] 402: Insufficient credits                     image=1/1 input=/Users/liuwei/Desktop/lowpoly/BIBAI1995090.png

how can I solve this problem ?
thanks

**Comment by groe** [comment]
Hi @zcdliuwei,

Thanks for reaching out. It seems like your account balance is insufficient. Please contact team@remove.bg for further help.
